name: Deploy WordPress Plugin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout cÃ³digo
        uses: actions/checkout@v4

      - name: Deploy a servidor FTP
        uses: airvzxf/ftp-deployment-action@v1.3.3
        with:
          server: 195.35.33.109
          user: u947001429.alex
          password: "?[FlyCR>bWoXhp6Q"
          local_dir: "./"
          remote_dir: "/wp-content/themes/arcano-astral/"
          ftp_ssl_allow: "false"
          ftp_passive_mode: "true"
          max_retries: "8"
          net_timeout: "40s"
          lftp_settings: "set ssl:verify-certificate false; set cmd:status-interval 2s;"
